name = "diemdanhqr"
main = "backend/src/index.js"
compatibility_date = "2024-01-01"

[vars]
APP_URL = "https://xudoanducmevonhiem.id.vn"
REDIRECT_URI = "https://xudoanducmevonhiem.id.vn/auth/callback"
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwa5jLbOhj2F7oHjBeLNDYpzObC8TGbHbgJ51pf8RLqIqCmxovGgCv_IYcYcCjuG7Mf4A/exec"

[triggers]
crons = [
  "30 2 * * SUN",
  "30 4 * * SUN",
  "0 13 * * TUE",
  "0 13 * * THU"
]

[assets]
directory = "frontend"
binding = "ASSETS"
run_worker_first = true

[env.preview.vars]
APP_URL = "https://dev.xudoanducmevonhiem.id.vn"
REDIRECT_URI = "https://dev.xudoanducmevonhiem.id.vn/auth/callback"
APPS_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwa5jLbOhj2F7oHjBeLNDYpzObC8TGbHbgJ51pf8RLqIqCmxovGgCv_IYcYcCjuG7Mf4A/exec"

[[d1_databases]]
binding = "DB"
database_name = "diemdanhqr-db"
database_id = "b9f439ae-5e08-44b9-b1ce-1d78f4dde1c2"
